### PR TITLE
Jpsb autocomplete and bug fix

### LINKED ISSUE #29: Bug: if user nominates twice, first nominations disappear
Kristiina nominated 15 brands, out of which 7 were new additions. When she got to share page, she clicked back button. The form only rememberd 7 of the brands she had nominated (looks like the ones that had already been in the database). She clicked nominate again.

In our database, it looks like she has nominated only 7 brands. 

This is a bug, because the initially nominated brands should be always kept.
If a user submits again, the second nomination should add to the first one, if there are any new ones, not remove any brands from the first nomination.

Screenshot from DB query showing the brands that she added on the first nomination, but that now say "0" nominations.

image

### PR DESCRIPTION
**Pull request by jpsb**
#29 #22

### CODE REVIEW

**Comment by ilonamm** [comment]
To me this seems to fix issue #29 perfectly 👍

**Comment by batmany13** [comment]
@jpsb please make sure the merge worked properly

File: web/controllers/brand_controller.ex [hunk 1]
```diff
@@ -1,21 +1,13 @@
...
-  filterable do
-    @options param: :q
-    filter search(query, value, _conn) do
-      query |> where([u], ilike(u.name, ^"%#{value}%"))
-    end
-  end
-
   def index(conn, params) do
-    with {:ok, query, filter_values} <- apply_filters(Brand, conn),
+    with {:ok, query, filter_values} <- Brand.apply_filters(conn),
```
Comment (batmany13) [inline web/controllers/brand_controller.ex:10]: good refactor 👍

**Review by batmany13 — APPROVED** [review]
